controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /api/products-with-discounts
    controller: App\Controller\ApiController::index